language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706_Maximova_All_Lab
  - make -j
  - ./Vector/Vector
  - ./VectorTest/VectorTest
  - ./Matrix/Matrix
  - ./MatrixTest/MatrixTest
  - ./Stack/Stack
  - ./StackTest/StackTest
  - ./Queue/Queue
  - ./QueueTest/QueueTest
notifications:
  email: false
